



services:
  api:
    build: .
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - DB_USER: ${DB_USER}
      - DB_HOST: db
      - DB_PASSWORD: ${DB_PASSWORD}
      - DB_NAME: ${DB_NAME}
      - DB_PORT: ${DB_PORT}
      - REDIS_PORT: ${REDIS_PORT}
      - REDIS_HOST: redis

    
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    environment:

      - POSTGRES_USER: ${DB_USER}
      - POSTGRES_PASSWORD: ${DB_PASSWORD}
      - POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - app-network


# Define custom network
networks:
  app-network:
    driver: bridge

